name: afq-insight-paper

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - requests
  - jupyterlab
  - ipywidgets
  - numpy
  - matplotlib
  - palettable
  - pip
  - pip:
      - dipy
      - "git+git://github.com/richford/AFQ-Insight.git#egg=afqinsight"
